spring:
  datasource:
    url: jdbc:h2:mem:database
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  devtools:
    livereload:
      enabled: true
    thymeleaf:
      cache: false
    restart:
      enabled: true

